Model: {
  Name: MPS,
  Sin: 196,
  Sout: 2,
  Initial bond dimension: 1,
  Maximum bond dimension: 128,
  Feature bond dimension: 2,
  Truncation: 0.0000000001,
  Feature Map: 0, 
}
Dataset: {
  Name: FP2, #this is not used by the program is just for claritity;
  From: /path/to/dataset,
}
Load and Save Module: {
  Restart: NO,
  From: model.pt,
  To: model.pt,
  Save every: 100,
}
Train: {
  Batch size: 120,
  Number of batches: 1,
}
Test: {
  Batch size: 30,
  Number of batches: 1,
}
Optimizer: {
  Adam: {
    lr: 0.002,
}
}

Number of epochs: 10000
USE_GPU: false 
